### ISSUE TITLE
Add configurable include/lib directories

### ISSUE THREAD

**Issue by Bakuriu** [nicity/CppTools#18]
I cannot find any way to configure the plugin so that it uses my include files and the headers for the libraries I'm using. This means that almost any identifier is considered as undefined and the plugin becomes pretty much useless for my use case.

It should be possible to add include directories to avoid this issue.

My use case: writing a Python extension using PyCharm 4.5. This requires adding the python libraries' include directory and the project include directory.

**Comment by nicity** [comment]
Have you tried Settings | Other Settings | C / C++ | Additional include directories ?

**Comment by Bakuriu** [comment]
No I haven't because I thought that the correct place for plugins settings was under Settings | Plugins, which evidently isn't. Using the search functionality isn't able to find any reference to "include" in Other Settings (although it is there; probably those texts aren't searched at all).
