### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by bbarker** [nicity/CppTools#5]
I'm curious what license CppTools is using. I'd like to integrate parts of it into another (open source) IntelliJ plugin, but don't want to step on any toes.

**Comment by jwjames83** [comment]
@bbarker did you ever get a response? I'd like to know this as well.

**Comment by Menci** [comment]
I want to know the license, too. I wonder whether it's FOSS or not.

**Comment by bbarker** [comment]
It [appears](http://programmers.stackexchange.com/questions/26548/what-is-the-default-software-license) that without a license, the code cannot be meaningfully used.

**Comment by nicity** [comment]
Added LICENSE.txt
