### ISSUE TITLE
Plugin is not compatible with Intellij 14.1

### ISSUE THREAD

**Issue by bkuberek** [nicity/CppTools#8]
Hi I just downloaded the latest 14.1 and the plugin was disabled.

build 141.177

![](http://cl.ly/image/1w281h3b2r2K/Image%202015-03-26%20at%202.15.27%20PM.png)!

**Comment by bkuberek** [comment]
By The way, thanks a lot for this plugin.

**Comment by andrzejsliwa** [comment]
Hi @nicity, any chance to relax build compatibility?

**Comment by andrzejsliwa** [comment]
I just update plugin.xml in CppTools.zip to **until-build="142.0"** and its seems to working on 14.1 ^^

**Comment by nicity** [comment]
Fixed in build 0.8.8

**Comment by andrzejsliwa** [comment]
Thx!
